CUSTOM_STOP = ['the', 'a ','us', 'sold', 'of', 'in', 'created', 'that', 'made', 'we\'ve', 'after', 'struggling','their','his','only','previously','leaving', 'et','c3s', 'otg',
                 'master', 'uls:', 'v4.0', 'efas', 'nan', 'rus', 'download', 'show', 'new', 'esa', 'use', 'free', 'service', 'access', 'learn', 'using', 'sar', 'acquired', 'analized',
                 'process', 'download', 'analyse', 'information', 'snap', 'visualize', 'employ', 'products', 'provides', 'efas', 'processing']

DC_DURATION_TERMS = {'e years': '3 years',
                   '1 hour 20 minutes': '<=1 day',
                   '3 5 years': '5 years',
                   '3 5 ans': '5 years',
                   '5 year': '5 years',
                   'one year': '1 year',
                   'e year ': '1 year',
                   'e year': '1 year',
                   '1 year ': '1 year',
                   't year ': '1 year',
                   '3 ans': '3 years',
                   '4 semestres': '2 years',
                   '2 hours': '<=1 day',
                   '1 jour': '<=1 day',
                   '2 semesters': '1 year',
                   '6 semesters': '3 years',
                   '12 months': '1 year',
                   '18 months': '3 semesters',
                   '5 days': '<=10 days',
                   '3 days': '<=10 days',
                   '2 days': '<=10 days',
                   '1': '<10 days',
                   '2 5 jours': '<=10 days',
                   '4 days': '<=10 days',
                   '6 semestres': '3 years',
                   '4 semesters': '2 years',
                   '1 day': '<=1 day',
                   '10 days': '<=10 days',
                   '2 jours': '<=10 days',
                   ' 12month ': '1 year'
                   }

DC_LANGUAGE = {'français': 'french',
               'french english': 'english french',
               'spanish english': 'english spanish',
               'anglais': 'english',
               'english français': 'english french',
               'english deutch': 'deutch english',
               'english  french': 'english french',
               'anglais espagnol': 'english spanish',
               'anglais italien': 'english italian',
               'italian english': 'english italian'
               }

DC_COUNTRY = {"Université Côte d'Azur (Nice, France)": 'PACA',
               ' Barcelona': 'Spain', 'Barcelona': 'Spain',
               ' Madrid': 'Spain', 'Madrid': 'Spain',
               ' Sevilla': 'Spain', 'Sevilla': 'Spain',
               'university park campus nottingham': 'England',
               'Espagne ': 'Spain',
               'Espagne': 'Spain',
               'distance': 'online course',
               ' on-line course': 'online course',
               ' à distance': 'online course'
               }

DC_ORGANISATION = {'Faculté des Sciences et Ingénierie Université Toulouse III - Paul Sabatier': 'Université Toulouse III',
                   "IUT Aix Marseille Université - site d'Aix-en-Provence": 'IUT Aix Marseille Université',
                   'Ecole Universitaire de Physique et dIngénierie  Université Clermont Auvergne': 'Université Clermont Auvergne',
                   'Faculté des Sciences (FDS) - Département Mécanique - Aix Marseille Université': 'IUT Aix Marseille Université',
                   'IUT Aix Marseille Université - site de Marseille St Jérôme': 'IUT Aix Marseille Université',
                   'IUT Aix Marseille Université - site de Salon-de-Provence - Dept. GEII': 'IUT Aix Marseille Université',
                   "Arts et Métiers - Campus d'Aix-en-Provence": "Campus d'Aix-en-Provence",
                   "Pôle Géographie, Aménagement, Environnement Université d'Aix-Marseille": 'IUT Aix Marseille Université',
                   'Faculté des Sciences (FDS) - Département de Physique - Aix Marseille Université': 'IUT Aix Marseille Université',
                   'IUT Aix Marseille Université - site de Digne-les-Bains': 'IUT Aix Marseille Université',
                   'Grenoble INP - Phelma': 'Grenoble INP',
                   'Grenoble INP - Ensimag': 'Grenoble INP',
                   'Grenoble INP - Ense3': 'Grenoble INP',
                   'Grenoble INP - Esisar': 'Grenoble INP'
                   }

DC_DIPLOMA = {" Diplôme dingénieur (French national engineering degree) ": 'French national Eng. degree',
               ' Vocational bachelor, three-year university vocational degree ': 'Vocational bachelor',
               ' BUT (three-year technological university degree) ': 'BUT',
               ' Mastère Spécialisé: French Grandes Ecoles Specialized (or Specializing) master ': 'Specialized master-Grandes Ecoles ',
               ' MSc : Master of Sciences degree from a French higher education Institute ': 'MSc-French higher ed. Institute',
               ' Certificate of participation (Notification of training attendance/completion) ': 'Training Certificate',
               ' BTS (Two-year technical diploma) ': 'BTS',
               ' Bachelor: three-year university degree ': 'Bachelor degree',
               ' Bachelor degree ': 'Bachelor degree',
               ' Certificate : training certificate (from a higher education institution ) ': 'Training certificate',
               ' Bachelor or Baccalaureat (Canada) ': 'Bachelor degree',
               ' MSc or MS : Master of Sciences (international) ': 'MSc-International'
            }

DC_LEVEL_REQUIRED = {" French baccalauréat + 3": 'Bac +3',
                   ' French baccalauréat + 2': 'Bac +2',
                   ' French baccalauréat + 0': 'Bac +0',
                   ' French baccalauréat + 4': 'Bac +4',
                   ' French baccalauréat + 5': 'Bac +5',
                   'Bachelor of Science (Licence in France)': 'Bac +0',
                   ' Magistère (master degree level from a French university or higher education Institute) ': 'Master degree',
                   ' Mastère (master degree level from a French academic institution) ': 'Master degree',
                   'Master degree ': 'Master degree',
                   'French baccalaureat + 4 years': 'Bac +4',
                   'BAC +4': 'Bac +4',
                   'BAC + 3': 'Bac +3',
                   'BAC +3': 'Bac +3',
                   'BAC +5': 'Bac +5',
                   ' Baccalauréat (French high school diploma), A level ': 'Bac +0',
                   'a 3 or 4-year bachelor or licence (French term) ': 'Bac +0'
                   }
